Trying to make npm install work.

diff --git a/bin/v-add-npm-install b/bin/v-add-npm-install
--- a/bin/v-add-npm-install
+++ b/bin/v-add-npm-install
@@ -45,10 +45,10 @@ check_hestia_demo_mode
 
 # Change to the application directory
 app_dir="$HOMEDIR/$user/web/$domain/private/nodeapp"
-if [ ! -d "$app_dir" ]; then
-    $BIN/v-log-action "$user" "Error" "Web" "NodeJS application directory not found for $domain."
-    exit 1
-fi
+# if [ ! -d "$app_dir" ]; then
+#     $BIN/v-log-action "$user" "Error" "Web" "NodeJS application directory not found for $domain."
+#     exit 1
+# fi
 
 # Source NVM for the user
 export NVM_DIR="$HOMEDIR/$user/.nvm"
